### ISSUE TITLE
QMM source and download is missing

### ISSUE THREAD

**Issue by eamonwoortman** [thecybermind/qmm#1]
Hey Cybermind,

First of, excuse me for using "issues" for trying to contact you. Since personal messaging has been removed, I didn't know of any other way of communicating.

Let me begin by complimenting you on Quake 3 Multimod. I've had the pleasure of using it alot of years ago for a simple plugin like my anti-curse plugin and a more complicated plugin like GameMonkey ScriptMod(http://www.moddb.com/mods/gamemonkey-scriptmod).
I love the simplicity of the plugin API and it still remains inspiring me in my daily life as a game programmer, as well as the fact it being opensource.

Obviously this has been years ago, and I haven't touched QMM since. Although I just got an email from someone who's asking if I could provide him with a link to the QMM binaries. Personally I would be interested in the source code as well. Unfortunatly, I noticed your old repository at SourceForge has purged.

So my question, or 'issue', is, when will you upload the binaries and sourcecode.

Many thanks,

Eamon 'dutchmeat' Woortman

**Comment by thecybermind** [comment]
Wow, surprised someone noticed it was down so fast! I was in the process of
transferring everything to github when I got busy with work. I will be
uploading the source soon (hopefully this weekend) and then I'll attempt to
use "Releases" on github to host the binaries.

**Comment by eamonwoortman** [comment]
Thanks for the quick reply, I look forward to inspect the source once again and I'm sure the person who wrote me the email would be joyful to see it's still being maintained in a sense.

**Comment by eamonwoortman** [comment]
Is there something I can do to decrease the workload on your end?(eg. test the RtCW and ET) version, or do you have it covered?
I'm not trying to push you, but I just wanted to say you're not alone here :)

**Comment by thecybermind** [comment]
all qmm repos imported to github. check my profile for all plugins and sdks and such
